apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kubernetes-cluster-shubhamgoel02
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: shubhamgoel02/nagp-bi-annual:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "30m"
        ports:
        - containerPort: 7100
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: kubernetes-cluster-shubhamgoel02
spec:
  selector:
    app: myapp
  ports:
  - port: 7100
    targetPort: 30158
    protocol: TCP
